# Generated by Django 4.2.13 on 2026-04-21 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='unique_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
