# Generated by Django 4.2.13 on 2026-04-21 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_communitygroup_members_communitygroup_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='ignored_by',
            field=models.ManyToManyField(blank=True, related_name='ignored_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
