# Generated by Django 4.2.13 on 2026-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='app_name',
            field=models.CharField(default='collection', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='resourcecategory',
            unique_together={('app_name', 'slug')},
        ),
    ]
