# Generated by Django 4.2.13 on 2026-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_resourcecategory_app_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('category', 'slug')},
        ),
    ]
