# Generated by Django 6.0 on 2025-12-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testprofiles", "0002_linkitem_created_at_linkitem_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="currently",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
